trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Replace the username and registry name here with your own details
# This step also uses an ACR_TOKEN specified as a secret variable
- script: |
    echo "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" | docker login ghcr.io -u krijnvanderburg --password-stdin
  displayName: 'Log in to Container Registry'
  env:
    ACR_TOKEN: $(ACR_TOKEN)

- task: DevcontainersCi@0
  inputs:
    # Change this to point to your image name
    imageName: 'ghcr.io/krijnvanderburg/python-devcontainer'
    # Change this to be your CI task/script
    subFolder: python
    runCmd: 'make ci-build'
    # sourceBranchFilterForPush allows you to limit which branch's builds
    # are pushed to the registry
    sourceBranchFilterForPush: refs/heads/main
