trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Replace the username and registry name here with your own details
# This step also uses an ACR_TOKEN specified as a secret variable
- script: |
    echo "$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" | docker login ghcr.io -u krijnvanderburg --password-stdin
  displayName: 'Log in to Container Registry'
  env:
    ACR_TOKEN: $(ACR_TOKEN)

- task: DevcontainersCi@0
  inputs:
    # Change this to point to your image name
    imageName: 'devcontainer.azurecr.io/example-dev-container'
    # Change this to be your CI task/script
    subFolder: python
    runCmd: 'make ci-build'
    # sourceBranchFilterForPush allows you to limit which branch's builds
    # are pushed to the registry
    sourceBranchFilterForPush: refs/heads/main
