trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: acrToken
  type: string
  default: ''

steps:
# Replace the username and registry name here with your own details
# This step also uses an ACR_TOKEN specified as a parameter
- script: |
    echo "$(acrToken)" | docker login ghcr.io -u krijnvanderburg --password-stdin
  displayName: 'Log in to Container Registry'

- task: DevcontainersCi@0
  inputs:
    # Change this to point to your image name
    imageName: 'ghcr.io/krijnvanderburg/python-devcontainer'
    # Change this to be your CI task/script
    subFolder: python
    runCmd: 'make ci-build'
    # sourceBranchFilterForPush allows you to limit which branch's builds
    # are pushed to the registry
    sourceBranchFilterForPush: refs/heads/main
